// <auto-generated />
namespace GameStore.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class mig004 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig004));
        
        string IMigrationMetadata.Id
        {
            get { return "201601240414179_mig004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
